USE [master]
GO

/****** Object:  Database [Sheadule]    Script Date: 27.04.2017 23:55:34 ******/
CREATE DATABASE [Sheadule]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sheadule', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Sheadule.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Sheadule_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Sheadule_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Sheadule] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sheadule].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Sheadule] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Sheadule] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Sheadule] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Sheadule] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Sheadule] SET ARITHABORT OFF 
GO

ALTER DATABASE [Sheadule] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Sheadule] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Sheadule] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Sheadule] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Sheadule] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Sheadule] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Sheadule] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Sheadule] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Sheadule] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Sheadule] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Sheadule] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Sheadule] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Sheadule] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Sheadule] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Sheadule] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Sheadule] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Sheadule] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Sheadule] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Sheadule] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Sheadule] SET  MULTI_USER 
GO

ALTER DATABASE [Sheadule] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Sheadule] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Sheadule] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Sheadule] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Sheadule] SET  READ_WRITE 
GO

