//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheduleEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableView
    {
        public string FACULTY_NAME { get; set; }
        public Nullable<int> COURSE_CODE { get; set; }
        public string GROUP_NUMBER { get; set; }
        public string BUILDING { get; set; }
        public string AUDITORIUM_NUMBER { get; set; }
        public Nullable<int> WEEK_NUMBER { get; set; }
        public string WEEKDAY_NAME { get; set; }
        public string TEACHER_NAME { get; set; }
        public string DISCIPLINE_NAME { get; set; }
        public string ACTIVITY_TYPE_NAME { get; set; }
        public string TIME_START { get; set; }
        public string TIME_END { get; set; }
        public Nullable<int> CROSSES { get; set; }
        public Nullable<System.DateTime> TYPE_TIME_START { get; set; }
        public Nullable<System.DateTime> TYPE_TIME_END { get; set; }
        public string TYPE_NAME { get; set; }
    }
}
