//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheduleEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMETABLE
    {
        public int LESSON_CODE { get; set; }
        public Nullable<int> WEEKDAY_CODE { get; set; }
        public Nullable<int> COURSE_CODE { get; set; }
        public Nullable<int> GROUP_CODE { get; set; }
        public Nullable<int> TEACHER_CODE { get; set; }
        public Nullable<int> DISCIPLINE_CODE { get; set; }
        public Nullable<int> ACTIVITY_TYPE_CODE { get; set; }
        public Nullable<int> AUDITORIUM_CODE { get; set; }
        public Nullable<int> WEEK_NUMBER { get; set; }
        public Nullable<int> TIME_CODE { get; set; }
        public Nullable<int> CROSSES { get; set; }
    
        public virtual ACTIVITY ACTIVITY { get; set; }
        public virtual AUDITORIUM AUDITORIUM { get; set; }
        public virtual DISCIPLINE DISCIPLINE { get; set; }
        public virtual GROUPS GROUPS { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        public virtual TIME TIME { get; set; }
        public virtual WEEKDAY WEEKDAY { get; set; }
    }
}
